######################################################### 
# 8 zone reticulation controller
# Switch 0 operates pump
# 1-7 switches for irrigation zones
# ----------------------------------------------------

substitutions:
  esp_home_name: reticulation
  device_name: retic
  upper_device_name: "Retic Controller"
  retic_controller: retic_control

# Controller switches 
  sprinkler_control: Controller
  zone_0_name: Pump
  zone_1_name: valve_1
  zone_2_name: valve_2
  zone_3_name: Valve_3
  zone_4_name: valve_4
  zone_5_name: valve_5
  zone_6_name: valve_6
  zone_7_name: valve_7

  sensor_update_frequency: 1s
  #uom: Min

  
globals:
  - id: retic_zone_number
    type: int
    restore_value: no
    initial_value: '0'


esphome:
  name: ${esp_home_name}
  friendly_name: ${upper_device_name}
  name_add_mac_suffix: false
  project: 
    name: esphome.web
    version: '1.0'

  on_boot: 
    priority: -100
    then: 
      # Set default state for Valve Status
      - text_sensor.template.publish:
          id: valve_status
          state: "Idle"
# Platform
esp8266:
  board: esp01_1m

font:
  - file: "gfonts://Roboto"
    id: roboto
    size: 10

  - file: "gfonts://Playfair Display"
    id: playfair
    size: 15 

image:
  - file: mdi:watering-can 
    id: wateringcan
    resize: 80x80   
    
# I2C configuration  
i2c:
  sda: GPIO 4
  scl: GPIO 5
  scan: true
  id: bus_a

mcp23017:
  - id: 'mcp23017_hub'
    address: 0x27  

time:
  - platform: homeassistant
    id: hastime

####################################
# SPI pins:
# GPIO 12 MISO
# GPIO 13 MOSI
# GPIO 14 CLK   
# GPIO 15 CS
####################################3
spi:
  clk_pin: GPIO 14  #Clock pin D5
  mosi_pin: GPIO 13 #DC pin D7
  
display:
  - platform: ssd1306_spi
    model: "SSD1306 128x64"
    cs_pin: GPIO 15   # Chip Select CS D8
    dc_pin: GPIO 12   # DIN (MISO)  D6
    reset_pin: GPIO 2 # D4 
    lambda: |-
      it.strftime(7,0, id(playfair), "%a-%b-%d  %H:%M", id(hastime).now());
      it.line(0, 15, 100, 15);
#      it.print(10, 15, id(roboto), "The time remaining is: ", id(time_remaining));
#      it.image(30, 30, id(wateringcan));
#      it.printf(15,20, id(roboto_20), "Retic Controller");



# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "RnbBGXHdu7V+GpKvFTM4FizBCWcj5lvNsapH4k3uBRM="

#ota:
#  password: "509ed13ad225c8e872d527180e62544d"

ota:
   password: "d67e59bb8aa158e80783cf7102503c2b"

# Allow provisioning Wi-Fi via serial
improv_serial:  

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
# Manual IP
  manual_ip:
    static_ip: 10.10.0.245
    gateway: 10.10.0.1
    subnet: 255.255.255.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
  #  ssid: "Reticulation Fallback Hotspot"
  #  password: "qVaHDks0BSIu"

captive_portal:
 
dashboard_import:
  package_import_url: github://esphome/example-configs/esphome-web/esp8266.yaml@main
  import_full_config: true

# To have a "next url" for improv serial
web_server:

#status_led:
#  pin:
#    # Pin D5 / GPI14
#    number: GPIO14
#    inverted: false  

###############################################
# Text sensors with general information.
###############################################

text_sensor:
# Expose Time Remaining for running zone as a sensor.
  - platform: template
    id: time_remaining
    name: $device_name Time Remaining
    update_interval: $sensor_update_frequency
    icon: "mdi:timer-sand"
    lambda: |-
      int seconds = round(id(retic_controller).time_remaining_active_valve().value_or(0));
      int days = seconds / (24 * 3600);
      seconds = seconds % (24 * 3600);
      int hours = seconds / 3600;
      seconds = seconds % 3600;
      int minutes = seconds /  60;
      seconds = seconds % 60;
        return {
          ((days ? String(days) + "d " : "") + 
          (hours ? String(hours) + "h " : "") +
          (minutes ? String(minutes) + "m " : "") +
          (String(seconds) + "s")).c_str()};

# Expose Valve Status as a sensor.
  - platform: template
    id: valve_status
    name: $device_name Status
    update_interval: never
    icon: "mdi:information-variant"


##############################################################
# Section to manage the sprinkler controller actions
#############################################################
sprinkler:
  - id: retic_controller
    main_switch: "Start-Stop"
    auto_advance_switch: $upper_device_name Auto Advance
    reverse_switch: $upper_device_name Reverse
    pump_start_pump_delay: 2s
    pump_stop_valve_delay: 2s
    valve_overlap: 1s
###################################################
## Adjust run times all sprinklers by multiplier
    multiplier_number:
      id: multiply_num
      name: "retic_multiplier"
      initial_value: 1
      min_value: 0.5
      max_value: 4
      step: 0.5
      icon: "mdi:timer-outline"
      mode: box
      on_value:
        then:
          - sprinkler.set_multiplier:
              id: retic_controller
              multiplier: !lambda 'return x;'

#########################################################
# Number of times to repeat full sprinkler cycle
    repeat_number: 
      id: repeat_num
      name: "retic_cycle_repeat"
      initial_value: 0
      min_value: 0
      max_value: 5
      step: 1
      restore_value: True
    #  disabled_by_default: False
      icon: "mdi:timer-outline"
      mode: BOX
      on_value: 
        then:
          - sprinkler.set_repeat:
              id: retic_controller
              repeat: !lambda "return x;" 


###########################################################
# Activate switch + pump, designate valve to operate
# MCP23017_Pin_A0 = Pump GPIO 
############################################################           
    valves:  
      - valve_switch: $zone_1_name
        enable_switch: Enable $zone_1_name
        pump_switch_id: pin_A0
        run_duration_number: 
          name: time_zone_1
          unit_of_measurement: s
          mode: BOX
          icon: mdi:timer-outline
          initial_value: 60
          min_value: 15
          max_value: 600
          step: 15
          restore_value: true
          disabled_by_default: false
        valve_switch_id: pin_A1   # GPIO of valve to trigger

      - valve_switch: $zone_2_name
        enable_switch: Enable $zone_2_name
        pump_switch_id: pin_A0
        run_duration_number:
          name: time_Zone_2
          unit_of_measurement: s
          mode: BOX
          icon: mdi:timer-outline
          initial_value: 60
          min_value: 15
          max_value: 600
          step: 15
          restore_value: true
          disabled_by_default: false
        valve_switch_id: pin_A2

      - valve_switch: $zone_3_name
        enable_switch: Enable $zone_3_name
        pump_switch_id: pin_A0
        run_duration_number:
          name: time_zone_3
          unit_of_measurement: s
          mode: BOX
          icon: mdi:timer-outline
          initial_value: 60
          min_value: 15
          max_value: 600
          step: 15
          restore_value: true
          disabled_by_default: false
        valve_switch_id: pin_A3
      
      - valve_switch: $zone_4_name
        enable_switch: Enable $zone_4_name
        pump_switch_id: pin_A0
        run_duration_number:
          name: time_zone_4
          unit_of_measurement: s
          mode: BOX
          icon: mdi:timer-outline
          initial_value: 60
          min_value: 15
          max_value: 600
          step: 15
          restore_value: true
          disabled_by_default: false
        valve_switch_id: pin_A4

      - valve_switch: $zone_5_name
        enable_switch: Enable $zone_5_name
        pump_switch_id: pin_A0
        run_duration_number:
          name: time_zone_5
          unit_of_measurement: s
          mode: BOX
          icon: mdi:timer-outline
          initial_value: 60
          min_value: 15
          max_value: 600
          step: 15
          restore_value: true
          disabled_by_default: false
        valve_switch_id: pin_A5

      - valve_switch: $zone_6_name
        enable_switch: Enable $zone_6_name
        pump_switch_id: pin_A0
        run_duration_number:
          name: time_zone_6
          unit_of_measurement: s
          mode: BOX
          icon: mdi:timer-outline
          initial_value: 60
          min_value: 15
          max_value: 600
          step: 15
          restore_value: true
          disabled_by_default: false
        valve_switch_id: pin_A6

      - valve_switch: $zone_7_name
        enable_switch: Enable $zone_7_name
        pump_switch_id: pin_A0
        run_duration_number:
          name: time_zone_7
          unit_of_measurement: s
          mode: BOX
          icon: mdi:timer-outline
          initial_value: 60
          min_value: 15
          max_value: 600
          step: 15
          restore_value: true
          disabled_by_default: false
        valve_switch_id: pin_A7

#######################################################
# Allocate valves/solenoids to GPIO
# Using IO expander MCP23017 with 8 GPIO pins A0 - A7
#######################################################
switch:
  - platform: gpio
    name: $zone_0_name
    id: pin_A0
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin A0
      number: 0
      mode:
        output: true
      inverted: false

  - platform: gpio
    name: $zone_1_name
    id: pin_A1
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin A1
      number: 1
      mode:
        output: true
      inverted: false

  - platform: gpio
    name: $zone_2_name
    id: pin_A2
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin A0
      number: 2
      mode:
        output: true
      inverted: false

  - platform: gpio  
    name: $zone_3_name
    id: pin_A3
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin A3
      number: 3
      mode:
        output: true
      inverted: false
      
  - platform: gpio  
    name: $zone_04_name
    id: pin_A4
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin A4
      number: 4
      mode:
        output: true
      inverted: false

  - platform: gpio  
    name: $zone_05_name
    id: pin_A5
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin A5
      number: 5
      mode:
        output: true
      inverted: false

  - platform: gpio  
    name: $zone_06_name
    id: pin_A6
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin A6
      number: 6
      mode:
        output: true
      inverted: False

  - platform: gpio  
    name: $zone_07_name
    id: pin_A7
    pin:
      mcp23xxx: mcp23017_hub
      # Use pin A7
      number: 7
      mode:
        output: true
      inverted: false

################################              
# Buttons for sundry actions
################################
button:
# Button to pause cycle  
  - platform: template
    id: sprinkler_pause
    name: "Pause"
    icon: "mdi:pause"
    on_press:
      then:
        - text_sensor.template.publish:
            id: valve_status
            state: "Paused"
        - sprinkler.pause: retic_controller

# Button to resume cycle
  - platform: template
    id: sprinkler_resume
    name: "Resume"
    icon: "mdi:run"
    on_press:
      then:
        - text_sensor.template.publish:
            id: valve_status
            state: "Resumed"
        - sprinkler.resume: retic_controller

# Button to shutdown system
  - platform: template
    id: sprinkler_shutdown
    name: "Shutdown"
    icon: "mdi:stop"
    on_press:
      then:
        - text_sensor.template.publish:
            id: valve_status
            state: "Idle"
        - sprinkler.shutdown: retic_controller

