######################################################################
# Front Door Pi generates mqtt publish msg when button pressed
# Topic = playTune
# ESP 8266 receives topic and generates ön_message trigger
# This triggers play.next on dfplayer
# Dfplayer sends "Doorbell Actioned" after tune played
#######################################################################
esphome:
  
  name: doorbell-1
  friendly_name: DoorBell-1

esp8266:
  board: huzzah

# Enable logging
logger:
  level: VERBOSE
# Pins used on esp8266 
uart:
  tx_pin: GPIO15
  rx_pin: GPIO13
  baud_rate: 9600

# Declare DFPlayer mini module
dfplayer:
  on_finished_playback:
    then:
      logger.log: 'DB1 tune played'

script:
  - id: PlayTune
    then:
    - logger.log: "Start dfplayer"
    - dfplayer.set_volume: 25
    - dfplayer.play_next:

#binary_sensor:
#  - platform: homeassistant
#    name: "Input boolean"
#    entity_id: input_boolean.state_home
    
# Enable Home Assistant API
api:
  encryption:
    key: "AnyLmlvPx8TPuf+82RzFUBeYwrutlIrIEY3gYJN27qQ="
 
  on_client_connected:
    - logger.log: "API client connected"

#Create a service for HASS to trigger via a service call
  services:
    - service: dfplayer_next
      then:
        - dfplayer.play_next

#Allow over the air updates
ota:
  platform: esphome
  password: "c60a6199eae2eab7f11591c2d57332c0"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
      ssid: "Doorbell-1 Fallback Hotspot"
      password: "yb9Zh7nUXOgF"

# Manual IP
  manual_ip:
    static_ip: 10.10.0.67
    gateway: 10.10.0.1
    subnet: 255.255.0.0

captive_portal:    


# MQTT setup see mqtt.yaml for parameters
#mqtt:
#  broker: 10.10.0.5
#  discovery: true
#  username: mymqtt
#  password: !secret mqtt_PW
#  reboot_timeout: 0s
  
# Send birth message to open mqtt connection  
#  birth_message:
#    topic: bellSetup
#    payload: online
# Send will message if connection lost
#  will_message:
#    topic: NoConnection
#    payload: Connection Lost DB1

#  keepalive: 60s
 
#  on_message:
#    topic: PlayTune
#    qos: 0
#    
#    then:
#    - dfplayer.start:
#    - dfplayer.set_volume: 25
#    - dfplayer.play_next:

#    - mqtt.publish:
#        topic: playedTune
#        payload: "DB1 Played Tune!"

      

    