esphome:
  name: doorbell-2
  friendly_name: DoorBell-2

esp8266:
  board: huzzah

uart:
  tx_pin: GPIO15
  rx_pin: GPIO13
  baud_rate: 9600

# Declare DFPlayer mini module
dfplayer:
  on_finished_playback:
    then:
     logger.log: "DB2 tune played"
   

# Enable logging
logger:
  level: VERBOSE
 
# Enable Home Assistant API
api:
  encryption:
    key: "JomRoeGXFqxigVSr6xL3ZHGQkN6p+1Rtd9RERMPWi/I="

  on_client_connected:
    - logger.log: "API client connected"

#Create a service for HASS to trigger via a service call
  services:
    - service: dfplayer_next
      then:
        - dfplayer.play_next    

#Allow over the air updates
ota:
  platform: esphome
  password: "4de8672c3031f66df0203df598c3007a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Manual IP
  manual_ip:
    static_ip: 10.10.0.68
    gateway: 10.10.0.1
    subnet: 255.255.0.0

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Doorbell-2 Fallback Hotspot"
    password: "ZBiF7IMmALzj"
    
captive_portal:

# MQTT setup see mqtt.yaml for parameters
#mqtt:
#  broker: 10.10.0.5
#  discovery: true
#  username: mymqtt
#  password: !secret mqtt_PW
#  reboot_timeout: 0s
#  id: play
# Send birth message to open mqtt connection  
#  birth_message:
#    topic: bellSetup
#    payload: online
#  on_message:
 
 #   topic: PlayTune
#    qos: 0
    
    
      

    